/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/skills/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Count */
        get: operations["skill_count_skills_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Skills */
        get: operations["search_skills_skills_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skill */
        get: operations["get_skill_skills__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/marketplace/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Marketplace Counts
         * @description Backs the homepage browse panels in one round trip.
         */
        get: operations["marketplace_counts_marketplace_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{slug}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs For Skill */
        get: operations["jobs_for_skill_skills__slug__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{slug}/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Courses For Skill */
        get: operations["courses_for_skill_skills__slug__courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Otp
         * @description Send a sign-in code.
         *
         *     Always reports success for a well-formed number, whether or not an account
         *     exists — otherwise the endpoint enumerates registered phone numbers.
         */
        post: operations["request_otp_auth_otp_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_me_profile_get"];
        /** Update Profile */
        put: operations["update_profile_me_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_me_profile_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Skill */
        post: operations["add_skill_me_profile_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/skills/{skill_slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Skill */
        delete: operations["remove_skill_me_profile_skills__skill_slug__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/{collection}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Entry */
        post: operations["add_entry_me_profile__collection__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile/{collection}/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Entry */
        put: operations["update_entry_me_profile__collection___entry_id__put"];
        post?: never;
        /** Remove Entry */
        delete: operations["remove_entry_me_profile__collection___entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Never touches a dependency, so it cannot cascade.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/deep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Deep
         * @description Readiness. Probes each dependency independently and in parallel.
         */
        get: operations["health_deep_health_deep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Ping */
        post: operations["enqueue_ping_tasks_ping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Status */
        get: operations["task_status_tasks__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasOut */
        AliasOut: {
            /** Surface Form */
            surface_form: string;
            /**
             * Script
             * @enum {string}
             */
            script: "latin" | "devanagari" | "transliteration";
        };
        /** CandidateProfileFull */
        CandidateProfileFull: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name?: string | null;
            /** Headline */
            headline?: string | null;
            /** Location State */
            location_state?: string | null;
            /** Location District */
            location_district?: string | null;
            /** Years Experience */
            years_experience: number;
            /** Education Level */
            education_level?: ("none" | "primary" | "secondary" | "higher_secondary" | "iti" | "diploma" | "graduate" | "postgraduate") | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Gender */
            gender?: ("female" | "male" | "other" | "prefer_not_to_say") | null;
            /**
             * Willing To Relocate
             * @default false
             */
            willing_to_relocate: boolean;
            /** Preferred Employment Type */
            preferred_employment_type?: ("full_time" | "part_time" | "contract" | "apprenticeship") | null;
            /** Expected Salary Min Inr */
            expected_salary_min_inr?: number | null;
            /** Expected Salary Max Inr */
            expected_salary_max_inr?: number | null;
            /** Notice Period */
            notice_period?: ("immediate" | "within_15_days" | "within_30_days" | "over_30_days") | null;
            /** Onboarding Completed At */
            onboarding_completed_at?: string | null;
            /** Skills */
            skills?: components["schemas"]["CandidateSkillOut"][];
            /** Experiences */
            experiences?: components["schemas"]["ExperienceOut"][];
            /** Educations */
            educations?: components["schemas"]["EducationOut"][];
            /** Certifications */
            certifications?: components["schemas"]["CertificationOut"][];
            /** Languages */
            languages?: components["schemas"]["LanguageOut"][];
            /** Preferred Roles */
            preferred_roles?: components["schemas"]["PreferredRoleOut"][];
            /** Preferred Locations */
            preferred_locations?: components["schemas"]["PreferredLocationOut"][];
            completeness?: components["schemas"]["ProfileCompleteness"];
        };
        /**
         * CandidateProfileUpdateFull
         * @description Every field optional: sections save independently, so a partial payload
         *     must not blank out fields the user was not editing.
         */
        CandidateProfileUpdateFull: {
            /** Full Name */
            full_name?: string | null;
            /** Headline */
            headline?: string | null;
            /** Location State */
            location_state?: string | null;
            /** Location District */
            location_district?: string | null;
            /** Years Experience */
            years_experience?: number | null;
            /** Education Level */
            education_level?: ("none" | "primary" | "secondary" | "higher_secondary" | "iti" | "diploma" | "graduate" | "postgraduate") | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Gender */
            gender?: ("female" | "male" | "other" | "prefer_not_to_say") | null;
            /** Willing To Relocate */
            willing_to_relocate?: boolean | null;
            /** Preferred Employment Type */
            preferred_employment_type?: ("full_time" | "part_time" | "contract" | "apprenticeship") | null;
            /** Expected Salary Min Inr */
            expected_salary_min_inr?: number | null;
            /** Expected Salary Max Inr */
            expected_salary_max_inr?: number | null;
            /** Notice Period */
            notice_period?: ("immediate" | "within_15_days" | "within_30_days" | "over_30_days") | null;
        };
        /** CandidateSkillAdd */
        CandidateSkillAdd: {
            /** Skill Slug */
            skill_slug: string;
            /**
             * Proficiency
             * @default 3
             */
            proficiency: number;
        };
        /** CandidateSkillOut */
        CandidateSkillOut: {
            skill: components["schemas"]["SkillOut"];
            /** Proficiency */
            proficiency: number;
            /**
             * Source
             * @enum {string}
             */
            source: "self_declared" | "inferred" | "assessed" | "certified";
        };
        /** CertificationOut */
        CertificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Issuing Body */
            issuing_body?: string | null;
            /** Credential Id */
            credential_id?: string | null;
            /** Issued On */
            issued_on?: string | null;
            /** Expires On */
            expires_on?: string | null;
            /** Nsqf Level */
            nsqf_level?: number | null;
            skill?: components["schemas"]["SkillOut"] | null;
        };
        /** ComponentHealth */
        ComponentHealth: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detail */
            detail?: string | null;
        };
        /** CourseDetail */
        CourseDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title En */
            title_en: string;
            /** Title Hi */
            title_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "online" | "offline" | "hybrid";
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "both";
            /** Duration Hours */
            duration_hours?: number | null;
            /** Fee Inr */
            fee_inr?: number | null;
            /** Nsqf Level */
            nsqf_level?: number | null;
            /** Qualification Pack Code */
            qualification_pack_code?: string | null;
            tenant: components["schemas"]["TenantOut"];
            /** Skills */
            skills?: components["schemas"]["CourseSkillOut"][];
        };
        /** CourseOut */
        CourseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title En */
            title_en: string;
            /** Title Hi */
            title_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "online" | "offline" | "hybrid";
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "hi" | "both";
            /** Duration Hours */
            duration_hours?: number | null;
            /** Fee Inr */
            fee_inr?: number | null;
            /** Nsqf Level */
            nsqf_level?: number | null;
            /** Qualification Pack Code */
            qualification_pack_code?: string | null;
            tenant: components["schemas"]["TenantOut"];
        };
        /** CoursePage */
        CoursePage: {
            /** Items */
            items: components["schemas"]["CourseOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CourseSkillOut */
        CourseSkillOut: {
            skill: components["schemas"]["SkillOut"];
            /** Level Taught */
            level_taught?: number | null;
        };
        /** DeepHealth */
        DeepHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** Environment */
            environment: string;
            /** Version */
            version: string;
            /** Components */
            components: components["schemas"]["ComponentHealth"][];
        };
        /** EducationOut */
        EducationOut: {
            /** Qualification */
            qualification: string;
            /** Institution */
            institution?: string | null;
            /** Specialisation */
            specialisation?: string | null;
            /** Education Level */
            education_level?: ("none" | "primary" | "secondary" | "higher_secondary" | "iti" | "diploma" | "graduate" | "postgraduate") | null;
            /** Year Completed */
            year_completed?: number | null;
            /**
             * Is Pursuing
             * @default false
             */
            is_pursuing: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ExperienceOut */
        ExperienceOut: {
            /** Employer Name */
            employer_name: string;
            /** Role Title */
            role_title: string;
            /** Location */
            location?: string | null;
            /**
             * Started On
             * Format: date
             */
            started_on: string;
            /** Ended On */
            ended_on?: string | null;
            /**
             * Is Current
             * @default false
             */
            is_current: boolean;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title En */
            title_en: string;
            /** Title Hi */
            title_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /** Location State */
            location_state?: string | null;
            /** Location District */
            location_district?: string | null;
            /**
             * Employment Type
             * @enum {string}
             */
            employment_type: "full_time" | "part_time" | "contract" | "apprenticeship";
            /** Experience Min Years */
            experience_min_years: number;
            /** Experience Max Years */
            experience_max_years?: number | null;
            /** Salary Min Inr */
            salary_min_inr?: number | null;
            /** Salary Max Inr */
            salary_max_inr?: number | null;
            /** Nsqf Level Min */
            nsqf_level_min?: number | null;
            tenant: components["schemas"]["TenantOut"];
            /** Skills */
            skills?: components["schemas"]["JobSkillOut"][];
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title En */
            title_en: string;
            /** Title Hi */
            title_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /** Location State */
            location_state?: string | null;
            /** Location District */
            location_district?: string | null;
            /**
             * Employment Type
             * @enum {string}
             */
            employment_type: "full_time" | "part_time" | "contract" | "apprenticeship";
            /** Experience Min Years */
            experience_min_years: number;
            /** Experience Max Years */
            experience_max_years?: number | null;
            /** Salary Min Inr */
            salary_min_inr?: number | null;
            /** Salary Max Inr */
            salary_max_inr?: number | null;
            /** Nsqf Level Min */
            nsqf_level_min?: number | null;
            tenant: components["schemas"]["TenantOut"];
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** JobSkillOut */
        JobSkillOut: {
            skill: components["schemas"]["SkillOut"];
            /** Importance */
            importance: number;
            /** Is Mandatory */
            is_mandatory: boolean;
        };
        /** LanguageOut */
        LanguageOut: {
            /** Language */
            language: string;
            /**
             * Proficiency
             * @default conversational
             * @enum {string}
             */
            proficiency: "basic" | "conversational" | "fluent" | "native";
            /**
             * Can Read
             * @default true
             */
            can_read: boolean;
            /**
             * Can Write
             * @default true
             */
            can_write: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** MarketplaceCounts */
        MarketplaceCounts: {
            /** Jobs */
            jobs: number;
            /** Courses */
            courses: number;
        };
        /** MembershipOut */
        MembershipOut: {
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "admin" | "member";
            tenant: components["schemas"]["TenantOut"];
        };
        /** OtpRequest */
        OtpRequest: {
            /** Phone */
            phone: string;
        };
        /** OtpRequestResponse */
        OtpRequestResponse: {
            /** Sent */
            sent: boolean;
            /** Expires In Seconds */
            expires_in_seconds: number;
            /** Debug Code */
            debug_code?: string | null;
        };
        /** OtpVerify */
        OtpVerify: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** PreferredLocationOut */
        PreferredLocationOut: {
            /** State */
            state: string;
            /** District */
            district?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** PreferredRoleOut */
        PreferredRoleOut: {
            /** Title */
            title: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * ProfileCompleteness
         * @description Drives the progress meter and tells the candidate what to do next.
         */
        ProfileCompleteness: {
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /** Missing */
            missing?: string[];
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** SkillCount */
        SkillCount: {
            /** Count */
            count: number;
        };
        /** SkillDetail */
        SkillDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Hi */
            name_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /**
             * Skill Type
             * @enum {string}
             */
            skill_type: "technical" | "core" | "generic";
            /** Nsqf Level */
            nsqf_level?: number | null;
            /** Aliases */
            aliases?: components["schemas"]["AliasOut"][];
        };
        /** SkillOut */
        SkillOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Hi */
            name_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /**
             * Skill Type
             * @enum {string}
             */
            skill_type: "technical" | "core" | "generic";
            /** Nsqf Level */
            nsqf_level?: number | null;
        };
        /** SkillPage */
        SkillPage: {
            /** Items */
            items: components["schemas"]["SkillOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SkillSearchHit
         * @description A search result plus why it matched — the UI shows the matched alias so a
         *     transliterated hit does not look like a mistake.
         */
        SkillSearchHit: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name En */
            name_en: string;
            /** Name Hi */
            name_hi?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Description Hi */
            description_hi?: string | null;
            /**
             * Skill Type
             * @enum {string}
             */
            skill_type: "technical" | "core" | "generic";
            /** Nsqf Level */
            nsqf_level?: number | null;
            /** Matched On */
            matched_on?: string | null;
            /**
             * Match Kind
             * @default text
             * @enum {string}
             */
            match_kind: "exact" | "prefix" | "alias" | "text";
        };
        /** TaskEnqueued */
        TaskEnqueued: {
            /** Job Id */
            job_id: string;
        };
        /** TaskStatus */
        TaskStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** TenantOut */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Tenant Type
             * @enum {string}
             */
            tenant_type: "employer" | "course_provider" | "personal";
            /** City */
            city?: string | null;
        };
        /** TokenPairOut */
        TokenPairOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Full Name */
            full_name?: string | null;
            /** Phone Verified At */
            phone_verified_at?: string | null;
            /** Preferred Locale */
            preferred_locale: string;
            /** Memberships */
            memberships?: components["schemas"]["MembershipOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    skill_count_skills_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillCount"];
                };
            };
        };
    };
    search_skills_skills_search_get: {
        parameters: {
            query: {
                /** @description Free text, any script */
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_skills_get: {
        parameters: {
            query?: {
                skill_type?: ("technical" | "core" | "generic") | null;
                nsqf_level?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_skills__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                q?: string | null;
                /** @description Filter by skill slug */
                skill?: string | null;
                location_state?: string | null;
                employment_type?: ("full_time" | "part_time" | "contract" | "apprenticeship") | null;
                nsqf_level_max?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_courses_get: {
        parameters: {
            query?: {
                q?: string | null;
                /** @description Filter by skill slug */
                skill?: string | null;
                mode?: ("online" | "offline" | "hybrid") | null;
                language?: ("en" | "hi" | "both") | null;
                max_fee_inr?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_courses__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    marketplace_counts_marketplace_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketplaceCounts"];
                };
            };
        };
    };
    jobs_for_skill_skills__slug__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    courses_for_skill_skills__slug__courses_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_otp_auth_otp_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_all_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    get_profile_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
        };
    };
    update_profile_me_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateProfileUpdateFull"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_onboarding_me_profile_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
        };
    };
    add_skill_me_profile_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateSkillAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_skill_me_profile_skills__skill_slug__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_entry_me_profile__collection__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_me_profile__collection___entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_entry_me_profile__collection___entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProfileFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_deep_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepHealth"];
                };
            };
        };
    };
    enqueue_ping_tasks_ping_post: {
        parameters: {
            query?: {
                note?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_status_tasks__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
