/** The component library.
 *
 * Built on Radix primitives and this project's own design tokens rather than
 * generated by the shadcn CLI. The CLI was tried first and reverted: it
 * installs a second dark-mode mechanism (`.dark` class) alongside the
 * `prefers-color-scheme` one already in use, duplicate `--background`,
 * `--foreground` and `--border` definitions in oklch, and a font override — so
 * its components would have rendered light inside this app's dark theme.
 *
 * The tokens in `globals.css` are the single source of colour. Nothing here
 * hardcodes one.
 *
 * Only what something renders lives here. A primitive kept "for later" costs a
 * dependency on every phone that loads the app, and the target device is an
 * entry-level Android on mobile data — so tabs and select were removed again
 * rather than shipped unused. Adding one back is a single install.
 */

export { Badge } from "@/components/ui/badge";
export { Button } from "@/components/ui/button";
// From the non-client module, so server components can style a button too.
export { buttonVariants } from "@/components/ui/button-variants";
export { ButtonLink } from "@/components/ui/button-link";
export { Card, CardBody, CardTitle } from "@/components/ui/card";
export { Section, SectionHeading, Logo } from "@/components/ui/layout";
export { Progress } from "@/components/ui/progress";
export { Skeleton } from "@/components/ui/skeleton";
