"""Widen NSQF level columns to accept half-levels

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-03

NSQF defines half-levels and the national data uses them: the real corpus
contains 2.5, 3.5, 4.5 and 5.5 alongside whole numbers. Every nsqf_level column
was Integer with CHECK BETWEEN 1 AND 10, so importing the national taxonomy
would fail outright.

Written by hand rather than autogenerated: Alembic does not diff CHECK
constraint bodies, so the constraint swap is invisible to --autogenerate.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# table, column, constraint name
_LEVEL_COLUMNS = [
    ("skills", "nsqf_level", "ck_skills_nsqf_level"),
    ("jobs", "nsqf_level_min", "ck_jobs_nsqf_level"),
    ("courses", "nsqf_level", "ck_courses_nsqf_level"),
]


def upgrade() -> None:
    for table, column, constraint in _LEVEL_COLUMNS:
        op.drop_constraint(constraint, table, type_="check")
        op.alter_column(
            table,
            column,
            existing_type=sa.Integer(),
            type_=sa.Numeric(3, 1),
            existing_nullable=True,
            postgresql_using=f"{column}::numeric(3,1)",
        )
        op.create_check_constraint(
            constraint, table, f"{column} IS NULL OR ({column} >= 1 AND {column} <= 10)"
        )

    # candidate_certifications.nsqf_level has no CHECK today; widen the type only.
    op.alter_column(
        "candidate_certifications",
        "nsqf_level",
        existing_type=sa.Integer(),
        type_=sa.Numeric(3, 1),
        existing_nullable=True,
        postgresql_using="nsqf_level::numeric(3,1)",
    )


def downgrade() -> None:
    # Half-levels cannot survive a narrowing cast, so they are rounded rather
    # than silently truncated. Anything at x.5 becomes x — lossy by necessity.
    op.alter_column(
        "candidate_certifications",
        "nsqf_level",
        existing_type=sa.Numeric(3, 1),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="round(nsqf_level)::integer",
    )
    for table, column, constraint in reversed(_LEVEL_COLUMNS):
        op.drop_constraint(constraint, table, type_="check")
        op.alter_column(
            table,
            column,
            existing_type=sa.Numeric(3, 1),
            type_=sa.Integer(),
            existing_nullable=True,
            postgresql_using=f"round({column})::integer",
        )
        op.create_check_constraint(
            constraint, table, f"{column} IS NULL OR ({column} BETWEEN 1 AND 10)"
        )
