"""registration module actors

Revision ID: f3bacbfd7b1d
Revises: b12371f6182b
Create Date: 2026-08-14 10:09:13.060882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3bacbfd7b1d'
down_revision: Union[str, None] = 'b12371f6182b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_accounts_hashed_key'), 'service_accounts', ['hashed_key'], unique=True)
    op.add_column('users', sa.Column('platform_role', sa.String(), nullable=True))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'platform_role')
    op.drop_index(op.f('ix_service_accounts_hashed_key'), table_name='service_accounts')
    op.drop_table('service_accounts')
    # ### end Alembic commands ###
