import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, Computed, ForeignKey, Index, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.core.database import Base

# Skill classification, per NSQF's split between job-specific and shared competencies.
SKILL_TYPES = ("technical", "core", "generic")

# How an alias is written. Transliteration matters as much as the other two: on a
# low-end Android keyboard people type Hindi words in Latin script (ADR-033).
ALIAS_SCRIPTS = ("latin", "devanagari", "transliteration")


class Skill(Base):
    """The atomic node of the taxonomy (ADR-004).

    Sprint 2 models the leaf only. The hierarchy above it — Sector Skill Council,
    Sector, Occupation, Qualification Pack, NOS — arrives in a later sprint, as do
    the typed SkillRelation edges that turn this into a graph.
    """

    __tablename__ = "skills"
    __table_args__ = (
        CheckConstraint("skill_type IN ('technical', 'core', 'generic')", name="ck_skills_type"),
        CheckConstraint(
            "nsqf_level IS NULL OR (nsqf_level BETWEEN 1 AND 10)",
            name="ck_skills_nsqf_level",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(unique=True, index=True)

    name_en: Mapped[str] = mapped_column()
    name_hi: Mapped[str | None] = mapped_column(default=None)
    description_en: Mapped[str | None] = mapped_column(default=None)
    description_hi: Mapped[str | None] = mapped_column(default=None)

    skill_type: Mapped[str] = mapped_column(default="technical")
    nsqf_level: Mapped[int | None] = mapped_column(default=None)

    # Generated by Postgres, never written by the application. English text gets
    # the english config; Hindi gets 'simple' because Postgres ships no Hindi
    # stemmer or stopword list (ADR-033).
    # Computed() is what stops SQLAlchemy from putting this in INSERT/UPDATE;
    # Postgres rejects any write to a GENERATED ALWAYS column.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('english', coalesce(name_en, '')), 'A') || "
            "setweight(to_tsvector('simple',  coalesce(name_hi, '')), 'A') || "
            "setweight(to_tsvector('english', coalesce(description_en, '')), 'C') || "
            "setweight(to_tsvector('simple',  coalesce(description_hi, '')), 'C')",
            persisted=True,
        ),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    aliases: Mapped[list["SkillAlias"]] = relationship(
        back_populates="skill", lazy="selectin", cascade="all, delete-orphan"
    )


class SkillAlias(Base):
    """A surface form that resolves onto a canonical skill.

    Without these the taxonomy only matches text already written in taxonomy
    terms, which no real job advert or candidate self-description ever is.
    """

    __tablename__ = "skill_aliases"
    __table_args__ = (
        UniqueConstraint("skill_id", "surface_form", name="uq_alias_skill_form"),
        CheckConstraint(
            "script IN ('latin', 'devanagari', 'transliteration')",
            name="ck_alias_script",
        ),
        Index("ix_skill_aliases_skill_id", "skill_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    skill_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("skills.id", ondelete="CASCADE"))
    surface_form: Mapped[str] = mapped_column()
    script: Mapped[str] = mapped_column()

    skill: Mapped["Skill"] = relationship(back_populates="aliases")
