import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Computed,
    ForeignKey,
    Index,
    Numeric,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.core.database import Base

# Skill classification, per NSQF's split between job-specific and shared competencies.
SKILL_TYPES = ("technical", "core", "generic")

# How an alias is written. Transliteration matters as much as the other two: on a
# low-end Android keyboard people type Hindi words in Latin script (ADR-033).
ALIAS_SCRIPTS = ("latin", "devanagari", "transliteration")


class Skill(Base):
    """The atomic node of the taxonomy (ADR-004).

    Sprint 2 models the leaf only. The hierarchy above it — Sector Skill Council,
    Sector, Occupation, Qualification Pack, NOS — arrives in a later sprint, as do
    the typed SkillRelation edges that turn this into a graph.
    """

    __tablename__ = "skills"
    __table_args__ = (
        CheckConstraint("skill_type IN ('technical', 'core', 'generic')", name="ck_skills_type"),
        CheckConstraint(
            "nsqf_level IS NULL OR (nsqf_level >= 1 AND nsqf_level <= 10)",
            name="ck_skills_nsqf_level",
        ),
        CheckConstraint("source IN ('nsqf', 'curated')", name="ck_skills_source"),
        Index("ix_skills_type_level", "skill_type", "nsqf_level"),
        Index("ix_skills_source", "source"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(unique=True, index=True)

    name_en: Mapped[str] = mapped_column()
    name_hi: Mapped[str | None] = mapped_column(default=None)
    description_en: Mapped[str | None] = mapped_column(default=None)
    description_hi: Mapped[str | None] = mapped_column(default=None)

    skill_type: Mapped[str] = mapped_column(default="technical")

    # --- NSQF identity (ADR-034) -------------------------------------
    # One Skill row is one National Occupational Standard. The code is the
    # stable national identifier; the title is not, and changes between
    # versions.
    nos_code: Mapped[str | None] = mapped_column(unique=True, index=True, default=None)
    nos_version: Mapped[str | None] = mapped_column(default=None)
    nos_type: Mapped[str | None] = mapped_column(default=None)  # Core | Non-Core
    # 'nsqf' for imported units, 'curated' for anything hand-authored.
    source: Mapped[str] = mapped_column(default="curated")
    # Numeric, not Integer: NSQF defines half-levels (2.5, 3.5, 4.5, 5.5) and
    # the national data uses them. Derived here -- the authoritative level sits
    # on the Qualification Pack, since a NOS carries none of its own.
    nsqf_level: Mapped[Decimal | None] = mapped_column(Numeric(3, 1), default=None)

    # How many current qualifications use this unit. Denormalised by the importer
    # rather than counted per row: it is the default browse ordering over 21,303
    # skills, and an ORDER BY over a correlated subquery cannot use an index.
    # Prominence is also the only ordering that makes the first page useful --
    # alphabetical leads with "0JT" and "10.1. Case Studies".
    qp_count: Mapped[int] = mapped_column(default=0, server_default="0", index=True)

    # Generated by Postgres, never written by the application. English text gets
    # the english config; Hindi gets 'simple' because Postgres ships no Hindi
    # stemmer or stopword list (ADR-033).
    # Computed() is what stops SQLAlchemy from putting this in INSERT/UPDATE;
    # Postgres rejects any write to a GENERATED ALWAYS column.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('english', coalesce(name_en, '')), 'A') || "
            "setweight(to_tsvector('simple',  coalesce(name_hi, '')), 'A') || "
            "setweight(to_tsvector('english', coalesce(description_en, '')), 'C') || "
            "setweight(to_tsvector('simple',  coalesce(description_hi, '')), 'C')",
            persisted=True,
        ),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(server_default=func.now(), onupdate=func.now())

    aliases: Mapped[list["SkillAlias"]] = relationship(
        back_populates="skill", lazy="selectin", cascade="all, delete-orphan"
    )


class SkillAlias(Base):
    """A surface form that resolves onto a canonical skill.

    Without these the taxonomy only matches text already written in taxonomy
    terms, which no real job advert or candidate self-description ever is.
    """

    __tablename__ = "skill_aliases"
    __table_args__ = (
        UniqueConstraint("skill_id", "surface_form", name="uq_alias_skill_form"),
        CheckConstraint(
            "script IN ('latin', 'devanagari', 'transliteration')",
            name="ck_alias_script",
        ),
        Index("ix_skill_aliases_skill_id", "skill_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    skill_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("skills.id", ondelete="CASCADE"))
    surface_form: Mapped[str] = mapped_column()
    script: Mapped[str] = mapped_column()

    skill: Mapped["Skill"] = relationship(back_populates="aliases")
